extends: airbnb
plugins:
- import
- jsx-a11y
- react
env:
  browser: true
rules:
  max-len: off
  react/jsx-filename-extension: off
  no-console: off
globals:
  shallow: true
  render: true
  mount: true